name: barz-denzler
channels:
        - anaconda
        - conda-forge
dependencies:
        - python=3.6
        - Cython
        - numpy
        - numexpr
        - pillow
        - cudatoolkit=9.0
        - nltk
        - scipy
        - scikit-learn
        - keras=2.2.5
        - tensorflow-gpu=1.8
        - matplotlib

# After having installed the conda environment, run pip install keras_applications=1.0.7 to patch a bug
